feat: Display helm command errors
This change captures stderr from helm commands. This changes the current
behavior of returning `exit status 1` to now include the reason for the
failure, ex:

```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists...
```

Signed-off-by: Brad Beam <brad.beam@b-rad.info>